version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: 'latest'

python:
  install:
    - method: uv
      command: sync
      path: python
      groups:
        - docs

sphinx:
  configuration: 'python/docs/source/conf.py'
  fail_on_warning: true

formats:
  - pdf
  - epub
  - htmlzip

submodules:
  include: all
